// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBv3w2LnjH07Ot6H9P1o78OrihvSU9mo0',
    appId: '1:566942069964:web:1c0b56ec69ec6bed6bbe69',
    messagingSenderId: '566942069964',
    projectId: 'todoapp-497ac',
    authDomain: 'todoapp-497ac.firebaseapp.com',
    storageBucket: 'todoapp-497ac.appspot.com',
    measurementId: 'G-QS742XEQJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPoQRjtDbz8b8W4cS3t4rnvyS46dM5gY',
    appId: '1:566942069964:android:990099a99649302e6bbe69',
    messagingSenderId: '566942069964',
    projectId: 'todoapp-497ac',
    storageBucket: 'todoapp-497ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzNddRLmIIRP7aXCPCRq9Q_qut7YD9LRE',
    appId: '1:566942069964:ios:ce349ad362ecd61a6bbe69',
    messagingSenderId: '566942069964',
    projectId: 'todoapp-497ac',
    storageBucket: 'todoapp-497ac.appspot.com',
    androidClientId: '566942069964-n7mpebrf38a1m06hb7ggsbaf3pg7kohf.apps.googleusercontent.com',
    iosClientId: '566942069964-pbs597k57v7fct6hmup8cvkr227tkhsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzNddRLmIIRP7aXCPCRq9Q_qut7YD9LRE',
    appId: '1:566942069964:ios:ce349ad362ecd61a6bbe69',
    messagingSenderId: '566942069964',
    projectId: 'todoapp-497ac',
    storageBucket: 'todoapp-497ac.appspot.com',
    androidClientId: '566942069964-n7mpebrf38a1m06hb7ggsbaf3pg7kohf.apps.googleusercontent.com',
    iosClientId: '566942069964-pbs597k57v7fct6hmup8cvkr227tkhsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
